---
host_role: laptop
host_platform_family: arch
host_desktop_stack: hyprland
host_gpu_stack:
  - amd-gpu
host_capabilities:
  - tlp
  - asus
  - netbird

managed_users:
  - name: daofficialwizard
    groups:
      - wheel

legacy_host_directory: hosts/firedragon
