#!/bin/bash
# Detects keyboard layout and applies necessary configurations.

set -e

# --- Header and Logging ---
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
log_info() { echo -e "\n${BLUE}[INFO]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }

# --- Keyboard Layout Detection ---
log_info "Detecting keyboard layout from /etc/vconsole.conf..."
VCONSOLE_CONF="/etc/vconsole.conf"
KEYBOARD_CONF_DIR="$HOME/.config/hypr/config"
KEYBOARD_CONF_FILE="$KEYBOARD_CONF_DIR/keyboard.conf"

if [ -f "$VCONSOLE_CONF" ]; then
  layout=$(grep '^XKBLAYOUT=' "$VCONSOLE_CONF" | cut -d= -f2 | tr -d '"')
  variant=$(grep '^XKBVARIANT=' "$VCONSOLE_CONF" | cut -d= -f2 | tr -d '"')

  mkdir -p "$KEYBOARD_CONF_DIR"
  echo "# Auto-generated by keyboard setup script" > "$KEYBOARD_CONF_FILE"
  echo "input {" >> "$KEYBOARD_CONF_FILE"
  
  if [[ -n "$layout" ]]; then
    echo "    kb_layout = $layout" >> "$KEYBOARD_CONF_FILE"
    log_info "Detected layout: $layout"
  fi

  if [[ -n "$variant" ]]; then
    echo "    kb_variant = $variant" >> "$KEYBOARD_CONF_FILE"
    log_info "Detected variant: $variant"
  fi
  
  echo "}" >> "$KEYBOARD_CONF_FILE"
  log_info "Keyboard configuration written to $KEYBOARD_CONF_FILE"
  log_warning "Please ensure you have 'source = ~/.config/hypr/config/keyboard.conf' in your main hyprland.conf."
else
  log_warning "/etc/vconsole.conf not found. Skipping auto-detection."
fi

# --- Apple Keyboard Fn-Key Fix ---
log_info "Checking for Apple keyboard..."
if lsusb | grep -iq "Apple, Inc. Keyboard"; then
  log_info "Apple keyboard detected. Applying Fn-key fix."
  if [[ ! -f /etc/modprobe.d/hid_apple.conf ]]; then
    echo "options hid_apple fnmode=2" | sudo tee /etc/modprobe.d/hid_apple.conf
    log_warning "The Apple keyboard fix has been applied. You may need to rebuild your initramfs for it to take effect (e.g., 'sudo mkinitcpio -P')."
  else
    log_info "Apple keyboard fix already in place."
  fi
else
    log_info "No Apple keyboard detected. Skipping fix."
fi

log_info "Keyboard setup complete."
