#!/bin/bash
# Detects keyboard layout and applies necessary configurations.

set -e

# Get script directory and source logging utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091  # Runtime-resolved path to logging library
source "${SCRIPT_DIR}/../../lib/logging.sh"

VCONSOLE_CONF="/etc/vconsole.conf"
KEYBOARD_CONF_DIR="$HOME/.config/hypr/config"
# Write host-specific detected settings into a separate file so it never conflicts
# with stow-managed base config (keyboard.conf).
KEYBOARD_CONF_FILE="$KEYBOARD_CONF_DIR/keyboard.local.conf"

if [ -f "$VCONSOLE_CONF" ]; then
  layout=$(grep '^XKBLAYOUT=' "$VCONSOLE_CONF" | cut -d= -f2 | tr -d '"')
  variant=$(grep '^XKBVARIANT=' "$VCONSOLE_CONF" | cut -d= -f2 | tr -d '"')

  mkdir -p "$KEYBOARD_CONF_DIR"
  echo "# Auto-generated by keyboard setup script" > "$KEYBOARD_CONF_FILE"
  echo "input {" >> "$KEYBOARD_CONF_FILE"
  
  if [[ -n "$layout" ]]; then
    echo "    kb_layout = $layout" >> "$KEYBOARD_CONF_FILE"
    log_info "Detected layout: $layout"
  fi

  if [[ -n "$variant" ]]; then
    echo "    kb_variant = $variant" >> "$KEYBOARD_CONF_FILE"
    log_info "Detected variant: $variant"
  fi
  
  echo "}" >> "$KEYBOARD_CONF_FILE"
  log_info "Keyboard configuration written to $KEYBOARD_CONF_FILE"
  log_warning "Please ensure you have 'source = ~/.config/hypr/config/keyboard.local.conf' in your main hyprland.conf."
else
  log_warning "/etc/vconsole.conf not found. Skipping auto-detection."
fi

# --- Apple Keyboard Fn-Key Fix ---
log_info "Checking for Apple keyboard..."
if lsusb | grep -iq "Apple, Inc. Keyboard"; then
  log_info "Apple keyboard detected. Applying Fn-key fix."
  if [[ ! -f /etc/modprobe.d/hid_apple.conf ]]; then
    echo "options hid_apple fnmode=2" | sudo tee /etc/modprobe.d/hid_apple.conf
    log_warning "The Apple keyboard fix has been applied. You may need to rebuild your initramfs for it to take effect (e.g., 'sudo mkinitcpio -P')."
  else
    log_info "Apple keyboard fix already in place."
  fi
else
    log_info "No Apple keyboard detected. Skipping fix."
fi

log_info "Keyboard setup complete."
