---
base_timezone: UTC
base_manage_time: true
base_firewall_enabled: false
base_polkit_admin_identities:
  - unix-group:wheel

base_bootloader_helper_src: "{{ playbook_dir }}/../../../scripts/lib/bootloader.sh"
base_bootloader_helper_path: /usr/local/libexec/dotfiles/bootloader.sh
