---
- name: Ensure modprobe directory exists
  ansible.builtin.file:
    path: /etc/modprobe.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install v4l2loopback modprobe config
  ansible.builtin.copy:
    src: "{{ v4l2loopback_role_files_root }}/etc/modprobe.d/v4l2loopback.conf"
    dest: /etc/modprobe.d/v4l2loopback.conf
    owner: root
    group: root
    mode: "0644"

- name: Ensure modules-load directory exists
  ansible.builtin.file:
    path: /etc/modules-load.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install v4l2loopback modules-load config
  ansible.builtin.copy:
    src: "{{ v4l2loopback_role_files_root }}/etc/modules-load.d/v4l2loopback.conf"
    dest: /etc/modules-load.d/v4l2loopback.conf
    owner: root
    group: root
    mode: "0644"
