---
iwd_enabled: true
iwd_service_name: iwd.service

iwd_managed_paths_by_host:
  goldendragon:
    - src: "{{ role_path }}/files/hosts/goldendragon/etc/iwd/main.conf"
      dest: /etc/iwd/main.conf
      mode: "0644"
