#!/usr/bin/env bash
set -euo pipefail

# openfortivpn-container entrypoint
# Responsibilities:
#   1. Validate environment and config
#   2. Start dnsmasq (background)
#   3. Start control plane (background)
#   4. Handle signals for graceful shutdown
#   5. Optionally auto-connect

VPN_HOST="${VPN_HOST:-}"
VPN_PORT="${VPN_PORT:-443}"
VPN_DOMAIN="${VPN_DOMAIN:-avular.dev}"
VPN_DNS_SERVERS="${VPN_DNS_SERVERS:-10.10.100.50,10.10.100.11}"
SAML_PORT="${SAML_PORT:-8020}"
DNS_METHOD="${DNS_METHOD:-auto}"
AUTO_CONNECT="${AUTO_CONNECT:-false}"
CONFIG_PATH="${CONFIG_PATH:-/etc/openfortivpn/config}"
API_TCP_PORT="${API_TCP_PORT:-8080}"
API_UNIX_SOCKET="${API_UNIX_SOCKET:-/run/openfortivpn/api.sock}"
LOG_LEVEL="${LOG_LEVEL:-info}"

HOST_RESOLV="${HOST_RESOLV:-/host/etc/resolv.conf}"
BACKUP_RESOLV="${BACKUP_RESOLV:-/var/lib/openfortivpn/resolv.conf.backup}"
DNSMASQ_PIDFILE="${DNSMASQ_PIDFILE:-/run/openfortivpn/dnsmasq.pid}"
DNSMASQ_CONF="${DNSMASQ_CONF:-/run/openfortivpn/dnsmasq.conf}"

log() {
  local level="$1"; shift
  echo "[entrypoint] [$level] $*" >&2
}

fatal() {
  log "FATAL" "$@"
  exit 1
}

validate() {
  if [[ -z "$VPN_HOST" && ! -f "$CONFIG_PATH" ]]; then
    fatal "VPN_HOST is not set and no config file found at $CONFIG_PATH"
  fi

  if [[ ! -f "$CONFIG_PATH" ]]; then
    log "INFO" "Generating seed config at $CONFIG_PATH"
    mkdir -p "$(dirname "$CONFIG_PATH")"
    cat > "$CONFIG_PATH" <<EOF
### Auto-generated by openfortivpn-container ###
host = ${VPN_HOST}
port = ${VPN_PORT}
EOF
  fi

  # Ensure config file is readable
  if [[ ! -r "$CONFIG_PATH" ]]; then
    fatal "Cannot read config file: $CONFIG_PATH"
  fi

  # Resolve real path of host resolv.conf if it's a symlink
  if [[ -L "$HOST_RESOLV" ]]; then
    local real_path
    real_path="$(readlink -f "$HOST_RESOLV" || true)"
    if [[ -n "$real_path" ]]; then
      HOST_RESOLV="$real_path"
      log "INFO" "Resolved symlinked resolv.conf to: $HOST_RESOLV"
    fi
  fi
}

setup_dnsmasq() {
  log "INFO" "Configuring dnsmasq..."
  mkdir -p "$(dirname "$DNSMASQ_CONF")" "$(dirname "$DNSMASQ_PIDFILE")"

  cat > "$DNSMASQ_CONF" <<EOF
# openfortivpn-container dnsmasq config
listen-address=127.0.0.1
bind-interfaces
no-resolv
no-poll
EOF

  # Add fallback DNS servers from host resolv.conf
  if [[ -f "$HOST_RESOLV" ]]; then
    local ns
    while IFS= read -r line; do
      if [[ "$line" =~ ^nameserver[[:space:]]+(.*)$ ]]; then
        ns="${BASH_REMATCH[1]}"
        if [[ "$ns" != "127.0.0.1" ]]; then
          echo "server=$ns" >> "$DNSMASQ_CONF"
        fi
      fi
    done < "$HOST_RESOLV"
  fi

  # Add VPN DNS servers for split domain
  local IFS=','
  local server
  for server in $VPN_DNS_SERVERS; do
    echo "server=/${VPN_DOMAIN}/${server}" >> "$DNSMASQ_CONF"
  done

  # Start dnsmasq
  dnsmasq --conf-file="$DNSMASQ_CONF" --pid-file="$DNSMASQ_PIDFILE"
  log "INFO" "dnsmasq started (pid: $(cat "$DNSMASQ_PIDFILE"))"
}

stop_dnsmasq() {
  if [[ -f "$DNSMASQ_PIDFILE" ]]; then
    local pid
    pid="$(cat "$DNSMASQ_PIDFILE")"
    if kill -0 "$pid" 2>/dev/null; then
      log "INFO" "Stopping dnsmasq (pid: $pid)..."
      kill -TERM "$pid" || true
      local waited=0
      while kill -0 "$pid" 2>/dev/null && (( waited < 5 )); do
        sleep 1
        waited=$((waited + 1))
      done
      kill -KILL "$pid" 2>/dev/null || true
    fi
    rm -f "$DNSMASQ_PIDFILE"
  fi
}

start_control_plane() {
  log "INFO" "Starting control plane..."
  export OPENFORTIVPN_HOST="$VPN_HOST"
  export OPENFORTIVPN_PORT="$VPN_PORT"
  export OPENFORTIVPN_DOMAIN="$VPN_DOMAIN"
  export OPENFORTIVPN_DNS_SERVERS="$VPN_DNS_SERVERS"
  export OPENFORTIVPN_SAML_PORT="$SAML_PORT"
  export OPENFORTIVPN_DNS_METHOD="$DNS_METHOD"
  export OPENFORTIVPN_AUTO_CONNECT="$AUTO_CONNECT"
  export OPENFORTIVPN_CONFIG_PATH="$CONFIG_PATH"
  export OPENFORTIVPN_API_TCP_PORT="$API_TCP_PORT"
  export OPENFORTIVPN_API_UNIX_SOCKET="$API_UNIX_SOCKET"
  export OPENFORTIVPN_LOG_LEVEL="$LOG_LEVEL"
  export OPENFORTIVPN_HOST_RESOLV="$HOST_RESOLV"
  export OPENFORTIVPN_BACKUP_RESOLV="$BACKUP_RESOLV"

  /usr/local/bin/openfortivpn-control-plane &
  CONTROL_PLANE_PID=$!
  log "INFO" "Control plane started (pid: $CONTROL_PLANE_PID)"
}

stop_control_plane() {
  if [[ -n "${CONTROL_PLANE_PID:-}" ]] && kill -0 "$CONTROL_PLANE_PID" 2>/dev/null; then
    log "INFO" "Stopping control plane (pid: $CONTROL_PLANE_PID)..."
    kill -TERM "$CONTROL_PLANE_PID" || true
    local waited=0
    while kill -0 "$CONTROL_PLANE_PID" 2>/dev/null && (( waited < 5 )); do
      sleep 1
      waited=$((waited + 1))
    done
    kill -KILL "$CONTROL_PLANE_PID" 2>/dev/null || true
  fi
}

cleanup() {
  log "INFO" "Shutdown signal received. Cleaning up..."
  stop_control_plane
  stop_dnsmasq
  log "INFO" "Cleanup complete."
  exit 0
}

main() {
  validate
  setup_dnsmasq
  start_control_plane

  # Handle signals
  trap cleanup INT TERM

  # Wait for control plane
  if [[ -n "${CONTROL_PLANE_PID:-}" ]]; then
    wait "$CONTROL_PLANE_PID"
  else
    # Fallback: sleep forever
    while true; do
      sleep 60 &
      wait $!
    done
  fi
}

main "$@"
