---
all:
  children:
    arch:
      hosts:
        dragon:
        firedragon:
        goldendragon:
    debian:
      hosts:
        microdragon:
    desktop:
      hosts:
        dragon:
        firedragon:
        goldendragon:
    laptop:
      hosts:
        firedragon:
        goldendragon:
    tlp:
      hosts:
        firedragon:
        goldendragon:
    asus:
      hosts:
        firedragon:
    hibernation:
      hosts:
        firedragon:
    server:
      hosts:
        microdragon:
    resolved:
      hosts:
        dragon:
        firedragon:
        goldendragon:
    hyprland:
      hosts:
        dragon:
        firedragon:
        goldendragon:
    sddm:
      hosts:
        dragon:
        firedragon:
        goldendragon:
    fingerprint:
      hosts:
        goldendragon:
    amd_gpu:
      hosts:
        dragon:
        firedragon:
    nvidia:
      hosts:
        goldendragon:
    netbird:
      hosts:
        dragon:
        firedragon:
        microdragon:
    fortinet_vpn:
      hosts:
        goldendragon:
