#!/bin/bash
THEMES_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/themes"

for dir in "$THEMES_DIR"/*/; do
    [ -d "$dir" ] && [ ! -L "${dir%/}" ] && echo "Updating: $(basename "$dir")" && git -C "$dir" pull
done
