keys:
  - &main_key age1uahdpm0gczrjg0ynp6f20np0dlx40tqjrqzwcnx67sg3dxuxyq6q5mqt4t

creation_rules:
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *main_key
  - path_regex: .*\.yml$
    key_groups:
      - age:
          - *main_key
  - path_regex: .*\.json$
    key_groups:
      - age:
          - *main_key
