keys:
  - &main_key age15tycxxawwpn6qln2wgpv00lzypzyvhts25eeajd003gemhn5hawqnj27aa

creation_rules:
  - path_regex: .*\.yaml$
    key_groups:
      - age:
          - *main_key
  - path_regex: .*\.yml$
    key_groups:
      - age:
          - *main_key
  - path_regex: .*\.json$
    key_groups:
      - age:
          - *main_key
