---
packages_by_platform:
  arch:
    core_cli:
      - vim
      - neovim
      - btop
      - fastfetch
      - fd
      - fzf
      - ripgrep
      - stow
      - unzip
      - wget
      - jq
      - bat
      - zoxide
      - lazygit
      - htop
      - tmux
      - tree
      - curl
      - rsync
      - age
      - zsh
    dev:
      - git
      - ansible
      - github-cli
      - python-pipx
  debian:
    core_cli:
      - vim
      - neovim
      - btop
      - fd-find
      - fzf
      - ripgrep
      - stow
      - unzip
      - wget
      - jq
      - bat
      - zoxide
      - lsd
      - htop
      - tmux
      - tree
      - curl
      - rsync
      - age
      - zsh
    dev:
      - git
      - ansible
      - gh
      - pipx
