---
- name: Edge-case ASUS laptop platform
  hosts: asus
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: asus_laptop

- name: Edge-case hibernation plumbing
  hosts: hibernation
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: hibernation

- name: Edge-case v4l2loopback kernel module
  hosts: v4l2loopback
  gather_facts: true
  any_errors_fatal: true

  roles:
    - role: v4l2loopback
